### ISSUE TITLE
Surrogate Keys usage/definition

### ISSUE THREAD

**Issue by ttrowell** [pantheon-systems/pantheon-advanced-page-cache#101]
I'm trying to figure out the best approach for implementing caching using the Advanced Page Caching plugin. I've gone over the documentation in the plugin repo, but I had some questions:

Is there a way to define a surrogate key for a WordPress query? I have a page https://xxx.org/news/ which only defines three surrogate keys: @post-214339 post-user-1 single@. This landing page is made up of a river of news articles, and I'd want to update this landing page if a new article is published. Will simply using the surrogate key for the landing page (@post-214339@) accomplish that, or is there a way to designate the custom query area (i.e., the river of articles) as having a surrogate key?

**Comment by rubas** [comment]
Just commited a PR #109 that allows you to change the purged keys for an event with a hook.

1. Use the hook `pantheon_wp_main_query_surrogate_keys` [[1]](https://github.com/pantheon-systems/pantheon-advanced-page-cache/blob/master/inc/class-emitter.php#L278) to add a specific surrogate key to the post
2. Use the hook `pantheon_purge_post_with_related`  [[2]](https://github.com/rubas/pantheon-advanced-page-cache/blob/aa430f13194fb3a5ebbca8ba30d15c08d7ae7482/inc/class-purger.php#L201) to purge

**Comment by ari-gold** [comment]
This looks great. Thanks for your contribution, @rubas !

@danielbachhuber @ttrowell I think we'll want to follow-up #109 with an update to the README and/or on pantheon.io/docs ? /cc @stevector @ataylorme

**Comment by danielbachhuber** [comment]
> I think we'll want to follow-up #109 with an update to the README and/or on pantheon.io/docs

Sure, good idea!
