### ISSUE TITLE
Wrong SurrogateKeys for Rest API w/ _embed

### ISSUE THREAD

**Issue by rubas** [pantheon-systems/pantheon-advanced-page-cache#102]
Using the rest api with the  [_embed](https://developer.wordpress.org/rest-api/using-the-rest-api/linking-and-embedding/#embedding) parameter messes up the surrogate keys.

`/wp-json/wp/v2/posts` => rest-post-collection rest-post-$id
`/wp-json/wp/v2/posts?_embed`  => rest-type_category-collection rest-term-xxx

WP: 4.8.2

**Comment by danielbachhuber** [comment]
Thanks for the report, @rubas. I've [tagged v0.2.1](https://github.com/pantheon-systems/pantheon-advanced-page-cache/releases/tag/v0.2.1) with a fix.
