### ISSUE TITLE
Unable to clear cache

### ISSUE THREAD

**Issue by AkshayMenariya** [pantheon-systems/pantheon-advanced-page-cache#105]
Hello Team,

I am using the pantheon predefined function to clear the cache in my custom plugins but it's not working.

Following function which i am using to send the purge request -:

To clear all cache -  `pantheon_wp_clear_edge_all();`
To clear cache for individual URL (page or post or custom post type)  - `pantheon_wp_clear_edge_paths( $paths = array() )`

Both function returns below error
`WP_Error Object ( [errors] => Array ( [pantheon_clear_edge_paths] => Array ( [0] => Unexpected result from Pantheon API when attempting to PURGE edge cache. ) ) [error_data] => Array ( ) ) `

Thanks
Akshay Menariya

**Comment by danielbachhuber** [comment]
Hi @AkshayMenariya,

Sorry to hear you're having trouble. Can you share the exact snippet of code you're using?

**Comment by AkshayMenariya** [comment]
Hi @danielbachhuber  ,

I am simply calling below function on when form successfully submitted to database.

`if (function_exists('pantheon_wp_clear_edge_all')) {
			$res = pantheon_wp_clear_edge_all();
			print_r($res );
		} `

Thanks
Akshay Menariya

**Comment by dustinleblanc** [comment]
Trying to test if the function works in general via WP-CLI:

```sh
terminus wp dustins-wordpress.dev -- shell
pantheon_wp_clear_edge_all()
=> bool(true)
```

**Comment by danielbachhuber** [comment]
@AkshayMenariya Could you update your existing support ticket with steps to reproduce the issue? I wasn't able to easily replicate in the `cse` environment.

Thanks!
