### ISSUE TITLE
Handling 404 [Enhancement]

### ISSUE THREAD

**Issue by rubas** [pantheon-systems/pantheon-advanced-page-cache#106]
I suggest emitting for a 404 response (`is_404()`) a `404` surrogate key and clearing it the same way as `front/home`.

This helps you to stay sane when people publish => unpublish => access “old” post url =>republish again.

**Comment by danielbachhuber** [comment]
👍 Good idea. Want to submit a PR for it?

**Comment by danielbachhuber** [comment]
Handled in #107
