### ISSUE TITLE
Document debug header to get `Surrogate-Key-Raw`

### ISSUE THREAD

**Issue by ari-gold** [pantheon-systems/pantheon-advanced-page-cache#119]
The Surrogate-Key-Raw header, used for debugging when using Pantheon Advanced Page Cache, is no longer sent by default. To receive this header when making a request, send the Pantheon-Debug: 1 header, like so:
```
 curl -IsH "Pantheon-Debug:1" https://example.com | grep key
```

This change addressed an issue that caused Twitter card validation to fail, and also reduces overall page size and speeds up page load time when sending many keys.

**Comment by danielbachhuber** [comment]
🔨

**Comment by danielbachhuber** [comment]
Oh, this causes our test suite to fail too https://circleci.com/gh/pantheon-systems/pantheon-advanced-page-cache/213

We need to pass the debug header in the request, d'oh. #121

**Comment by danielbachhuber** [comment]
> We need to pass the debug header in the request, d'oh.

This is fixed now 🔨
