### ISSUE TITLE
Consider page cache exemption options 

### ISSUE THREAD

**Issue by carl-alberto** [pantheon-systems/pantheon-advanced-page-cache#125]
Would it be possible if this plugin has the option to exempt certain pages as an alternative way in [Excluding Specific Pages from Caching](https://pantheon.io/docs/cache-control/#exclude-specific-pages-from-caching) 

Would love to try for a PR with this if it is feasible

**Comment by danielbachhuber** [comment]
> Would it be possible if this plugin has the option to exempt certain pages as an alternative way in [Excluding Specific Pages from Caching](https://pantheon.io/docs/cache-control/#exclude-specific-pages-from-caching)

This should be possible with a filter, no? Can you describe in a bit more detail what your proposed implementation would be?

**Comment by carl-alberto** [comment]
Let's say we want to exclude the `news` page in being cached, as per instructions in [Excluding Specific Pages from Caching](https://pantheon.io/docs/cache-control/#exclude-specific-pages-from-caching) we need to add this code in the theme's function.php

```
$regex_path_patterns = array(
  '#^/news/?#',
);

// Loop through the patterns.
foreach ($regex_path_patterns as $regex_path_pattern) {
  if (preg_match($regex_path_pattern, $_SERVER['REQUEST_URI'])) {
    add_action( 'send_headers', 'add_header_nocache', 15 );

    // No need to continue the loop once there's a match.
    break;
  }
}
function add_header_nocache() {
      header( 'Cache-Control: no-cache, must-revalidate, max-age=0' );
}


```

Would it be a good addition to this plugin's settings to have a section where to add urls to exclude in the cache as an alternative to the above instructions? https://screencast.com/t/V8wQj95c8C
