### ISSUE TITLE
Create developer API for emitting surrogate keys and triggering PURGE's

### ISSUE THREAD

**Issue by kibra** [pantheon-systems/pantheon-advanced-page-cache#16]
APIs:

* [x] `pantheon_wp_clear_edge_keys( $keys )`
* [x] `pantheon_wp_clear_edge_paths( $paths )`
* [x] `pantheon_wp_clear_edge_all()`

Documentation:

* [x] Each of the API functions you can use.
* [x] How to emit your own surrogate keys.
* [x] How to trigger your own purge events.
* [x] Determine sidebars rendered on a page, and purge the sidebar when widget is updated.
* [ ] Determine options in use on a page, and purge the option surrogate key when it's updated. Related #15

**Comment by danielbachhuber** [comment]
I'll do a first pass on this, then hand off for review when ready.

**Comment by danielbachhuber** [comment]
@kibra @ari-gold The README is now ready for a read + feedback: https://github.com/pantheon-systems/pantheon-integrated-cdn#pantheon-integrated-cdn
