### ISSUE TITLE
WP admin settings UI for plugin

### ISSUE THREAD

**Issue by kibra** [pantheon-systems/pantheon-advanced-page-cache#17]
Pantheon to specify exactly, so still TBD.  Roughly:
- UI presence to confirm plugin is installed
- Developer documentation on how to extend surrogate keys

**Comment by ari-gold** [comment]
@danielbachhuber Is it possible to add a section to existing "Pantheon Cache" tab provided by the mu-plugin when this plugin is activated? If not, then please just add a separate "Pantheon Advanced Page Cache" tab

<img width="1311" alt="pantheon-advanced-page-cache-ui" src="https://cloud.githubusercontent.com/assets/7874556/19951378/e203c092-a11a-11e6-801b-cfd34b2af98a.png">

copy:

Pantheon Advanced Page Cache

Pantheon Advanced Page Cache is enabled, which automatically purges related content from the Pantheon Edge.

Even with a high Default Cache Time, your visitors will never have to wait for fresh content. We recommend setting a Default Cache Time like 86400 seconds (1 day) in the field above.

To learn more see https://github.com/pantheon-systems/pantheon-advanced-page-cache

**Comment by danielbachhuber** [comment]
> Is it possible to add a section to existing "Pantheon Cache" tab provided by the mu-plugin when this plugin is activated

Sure, we can do that.

**Comment by danielbachhuber** [comment]
@kibra @ari-gold this is now in place

**Comment by ari-gold** [comment]
Looks good. Thanks @danielbachhuber!
