### ISSUE TITLE
Success admin notice has escaped markup

### ISSUE THREAD

**Issue by westonruter** [pantheon-systems/pantheon-advanced-page-cache#178]
I updated the settings and the success message shows a link that has its link HTML escaped:

![image](https://user-images.githubusercontent.com/134745/117357503-e0212600-ae69-11eb-82e7-bd60f26e388a.png)

**Comment by danielbachhuber** [comment]
Thanks for the heads up! I've created an upstream pull request for it: https://github.com/pantheon-systems/WordPress/pull/279
