### ISSUE TITLE
WordPress Multisite site network cache clearing issue

### ISSUE THREAD

**Issue by bananastalktome** [pantheon-systems/pantheon-advanced-page-cache#196]
Is this plugin (or the bundled MU pantheon-page-cache.php basic cache functionality) intended for Pantheon Multisite network environments? In testing on the Pantheon platform in a Multisite network environment, it seems that the cache is not isolated per blog. When, for example, a page is edited is one blog, all blogs containing pages with that ID as well as all blogs home caches are cleared. Would including the current blog ID:

```php
// untested
add_filter('pantheon_wp_main_query_surrogate_keys', function($keys) {
  // Add the blog ID to each key for network compatibility
  return array_map(function($k){ return "blog-" . get_current_blog_id() . "-$k"; }, $keys);
}, 9999, 1);
```
work as a way of making the surrogate keys unique to each blog? I assume there would still be issues other parts of cache clearing as well, but I haven't poked into that too much since I wanted to first make sure this plugin was Intended for multisite network environments.

**Comment by jspellman814** [comment]
Thanks for this report @bananastalktome. We are tracking internally as BUGS-5990 and are planning to address this sprint.

**Comment by bananastalktome** [comment]
@jspellman814 Tested and seems to work great, thank you very much! Only minor thing which would be nice to see added would be to maybe have another filter before https://github.com/pantheon-systems/pantheon-advanced-page-cache/blob/8f9f7f557a53941b30c1e73d11976ef3a36ea431/inc/class-emitter.php#L293-L294 to provide a way for us to add additional keys to the list before they are passed to `pantheon_wp_prefix_surrogate_keys_with_blog_id`, so prefixes are added for us. Not sure if this should be a separate issue or not.

Thanks again!

**Comment by jspellman814** [comment]
@bananastalktome No problem, that's a reasonable request. I've created a new ticket, CMSP-377, to track that work internally.
