### ISSUE TITLE
[BUGS-5914] Do not send `Surrogate-Key` header when an internal REST request is dispatched

### ISSUE THREAD

**Issue by felixarntz** [pantheon-systems/pantheon-advanced-page-cache#217]
WordPress core supports issuing "internal" REST requests, i.e. calling any registered REST endpoints without actually making a HTTP request to the REST API, e.g. just calling it in a regular WordPress request.

This is heavily used for example in the block editor to preload resources so that that data doesn't all have to be fetched through _actual_ REST requests after the initial page load (as that would cause a notable delay to the end user).

On my Pantheon site I am experiencing PHP warnings because this plugin is sending PHP headers `Surrogate-Key` _unconditionally_, even when the REST API is just being accessed within a regular WordPress request. This causes PHP warnings about output having already started every time I open the block editor.

The corresponding logic in the `Emitter::filter_rest_post_dispatch()` method needs to be fixed. The corresponding filter is also run for internal REST API calls, so the method needs to received some extra condition, so that it only sends the header when it is an _actual_ REST API request. The simplest way is to probably only send the header if the `REST_REQUEST` constant is set to `true`.

**Comment by kporras07** [comment]
Thanks for the report. Tracking it internally as BUGS-5914

**Comment by pwtyler** [comment]
@felixarntz, I am triaging #237, looks like this would address this issue, can you confirm?

**Comment by felixarntz** [comment]
@pwtyler Indeed, thanks, that looks right!

**Comment by jazzsequence** [comment]
closed via #237
