### ISSUE TITLE
Question about clearing cache on query blocks

### ISSUE THREAD

**Issue by brachypelma** [pantheon-systems/pantheon-advanced-page-cache#221]
Apologies for the rookie question, as I am getting my bearings with this plugin.

I am working on a fairly large/complex site that uses a Full-Site Editing theme. This site has several custom post types and pages with Gutenberg query blocks, each querying for content by various parameters.

I was trying to figure out how to clear the cache on any page that has a query block querying for a given content type when a new post of that content type is published. For now, I am using `pantheon_clear_edge_paths` to manually clear the cache on the pages I know have the relevant query blocks in them, e.g.:

```php
function custom_cache_clear_on_save_post() {
  add_action( 'save_post', 'custom_clearcache_archive_page' );
}

function custom_clearcache_archive_page( $post_id ){
  if ( get_post_type() === 'post' ) {
    pantheon_clear_edge_paths([
      '/giving/',
      '/news/news-room/',
      '/giving/why-give/',
    ]);
  }
}
```

But this approach is not ideal, since it involves hard-coding a set of paths that are subject to change as site authors add/remove pages and query blocks on the page. Ideally, there would be a way to clear the cache on any page where a query block exists that queries for a given post type whenever a post of that type is published.

Is there any way to automate this process with the plugin as it currently exists?

**Comment by jazzsequence** [comment]
So I am clear on the request, you are looking for a way for the plugin to be aware of content changes made to Gutenberg-based pages to add those page paths to a dynamic list if those pages have Query Blocks?

I think that manually managing a list in one form or other might be the only way to do this because I don't know that Gutenberg is particularly good at being aware of its own content such that it could flag a post on save as having -- or not having -- a particular type of block. 

However, if you could evaluate the post content on save to _check_ what types of blocks existed in a post, then you could probably update some setting or transient or something to maintain a running list of paths to clear. It would necessarily make `save_post` slower, though, because not only would you be running the `pantheon_clear_edge_paths` request, you'd also need to evaluate the markup in the post itself to look for the query block, which isn't going to be very efficient (unless there's some way of indexing the types of blocks in a Gutenberg post that I'm not aware of), so you may be better off with the manual list.  You _could_ move that list to the admin, so you make your editors or whomever responsible for adding/updating the list of pages so it's not just managed in the source code, but I don't know of any particular tricks to do what you're trying to do better than you already are beyond that.

**Comment by brachypelma** [comment]
Thank you for your reply, @jazzsequence.

I think the desired outcome is slightly different from what you described (though I may have just misunderstood your paraphrase of my original question). Basically:

1. I have various pages with WP core query blocks on them which query for different types of content.
2. That list of pages with query blocks is subject to change as site authors add/remove/edit pages.
3. When new posts get published, I want to clear the cache on whatever pages have query blocks that query for the type of content that was just published (e.g., if someone publishes a new post, I want all pages with query blocks querying for posts to get their cache cleared).

After sleeping on it, I think I arrived at a solution. Schematically, I added a `save_post` hook to my `functions.php` that does the following:

1. Queries for pages that have a query block in them.
2. Locates the `postType` property of each query block found to determine what kind of post it queries for
3. Gathers the URL paths of all the pages with query blocks into separate arrays, grouped by content type.
4. Passes the array of page URL paths for pages matching the content type of the post just published to `pantheon_clear_edge_paths` so that the cache for all the pages with queries querying for the relevant content type gets cleared.

It's fairly laborious implementing this, but I think this gets the job done.

**Comment by jazzsequence** [comment]
Glad you found a solution. If you're willing, it would be great if you wanted to share a draft of your solution for posterity and people (or, you know, AI) looking for an answer for this issue in the future.

**Comment by brachypelma** [comment]
. I had to modify/redact a bit of this in order to make this more generic/general purpose. I haven't tested the modified version below, so please proceed with caution (and please let me know if this is buggy or can otherwise be improved). In my case, I call `custom_cache_clear_on_save_post` in my `functions.php` file. I hope it's clear enough what's going on.

```php
<?php

function get_query_block_content_type( $blocks ) {
  foreach( $blocks as $block ) { // Search blocks for query block
    if ( $block['blockName'] === 'core/query' ) { // Extract queried content type from query block
      $attrs = $block['attrs'];
      $has_attrs = isset( $attrs ) && count( $attrs ) > 0;
      $query = $has_attrs ? $attrs['query'] : false;
      $has_query = isset( $query ) && count( $query ) > 0;
      $content_type = $has_query ? $query['postType'] : false;
      
      return $content_type;
    }

    $inner_blocks = $block['innerBlocks'];
    
    // Recursively search innerBlocks for query block
    if ( isset( $inner_blocks ) && count( $inner_blocks ) > 0 ) {
      $query_block_type = get_query_block_content_type( $inner_blocks );

      if ( $query_block_type ) {
        return $query_block_type;
      }
    }
  }

  return false;
}

function get_clearcache_data( $pages, $type ) {
  // Construct associative arrays to pass to `pantheon_clear_edge_paths`
  $data = array();
  $data['type'] = $type;
  $data['paths'] = array();

  foreach( $pages as $page ) {
    $permalink = get_permalink( $page );
    $url = $permalink ? parse_url( $permalink ) : false;
    $path = $url && isset( $url['path'] ) ? $url['path'] : false;

    if ( $path ) {
      array_push( $data['paths'], $path );
    }
  }

  return $data;
}

function get_pages_with_query_blocks_data() {
  $all_pages = get_pages();
  $pages_with_query_block = array();
  $post_query_pages = array();
  $custom_content_type_query_pages = array();
  $clearcache_data = array();

  foreach( $all_pages as $page ) {
    if ( has_block( 'core/query', $page ) ) {
      array_push( $pages_with_query_block, $page );
    }
  }

  foreach( $pages_with_query_block as $page ) {
    $blocks = parse_blocks( $page->post_content );
    $type = get_query_block_content_type( $blocks );

    if ( !$type ) {
      continue;
    }

    if ( $type === 'custom_content_type' ) {
      array_push( $custom_content_type_query_pages, $page );
    } elseif ( $type === 'post' ) {
      array_push( $post_query_pages, $page );
    }
  }

  if ( count( $custom_content_type_query_pages ) > 0 ) {
    array_push( $clearcache_data, get_clearcache_data( $custom_content_type_query_pages, 'custom_content_type' ) );
  }
  if ( count( $post_query_pages ) > 0 ) {
    array_push( $clearcache_data, get_clearcache_data( $post_query_pages, 'post' ) );
  }

  return count( $clearcache_data ) > 0 ? $clearcache_data : false;
}

function custom_clearcache_archive_page( $post_id ){
  $data = get_pages_with_query_blocks_data();

  if ( !$data || count( $data ) === 0 ) {
    return;
  }

  foreach( $data as $datum ) {
    if ( count( $datum['paths'] ) > 0 && get_post_type() === $datum['type'] ) {
      pantheon_clear_edge_paths( $datum['paths'] );
    }
  }
}

function custom_cache_clear_on_save_post() {
  add_action( 'save_post', 'custom_clearcache_archive_page' );
}
```

**Comment by jazzsequence** [comment]
Thanks @brachypelma!

**Comment by wwahammy** [comment]
@brachypelma just wanted to thank you for the work: I have the EXACT same problem.

**Comment by wwahammy** [comment]
I added an [issue](https://github.com/pantheon-systems/pantheon-advanced-page-cache/issues/383) describing this problem more generally and a plan for a possible solution.
