### ISSUE TITLE
Rename plugin to pantheon-advanced-page-cache

### ISSUE THREAD

**Issue by ari-gold** [pantheon-systems/pantheon-advanced-page-cache#23]

**Comment by danielbachhuber** [comment]
@ari-gold Did you get to a final decision on this?

**Comment by ari-gold** [comment]
@danielbachhuber Yes, please move forward with this one.

**Comment by danielbachhuber** [comment]
@ari-gold I've:

* Renamed all strings, files, and references generally within the plugin to Pantheon Advanced Page Cache.
* Created a new `pantheon-advanced-page-cache` site for AC testing and automated builds. The latest copy of the plugin is uploaded to the dev site.
* Registered the plugin with WordPress.org. It will eventually live here: https://wordpress.org/plugins/pantheon-advanced-page-cache/

We still need to:

* [ ] Rename this repository to `pantheon-advanced-page-cache`.
* [ ] Set up Circle and Travis to follow the project after the rename, and add the appropriate environment variables in Circle (`TERMINUS_TOKEN` and `GITHUB_TOKEN`).

**Comment by danielbachhuber** [comment]
Looks like Circle gracefully handled the rename, so good to go.
