### ISSUE TITLE
All posts in same category should not be purged when one of the posts is updated

### ISSUE THREAD

**Issue by ari-gold** [pantheon-systems/pantheon-advanced-page-cache#28]
Steps to reproduce
1. Create two posts
2. Update one of the posts

Expected
Post updated should be purged

Actual
Both posts are purged

```
$ curl -I http://dev-pantheon-integrated-cdn.pantheonsite.io/2016/11/03/post-1 --silent | grep Age
Age: 47
 $ curl -I http://dev-pantheon-integrated-cdn.pantheonsite.io/2016/11/03/post-2 --silent | grep Age
Age: 33
 $ curl -I http://dev-pantheon-integrated-cdn.pantheonsite.io/ --silent | grep Age
Age: 51
$ # UPDATE POST 2
$ curl -I http://dev-pantheon-integrated-cdn.pantheonsite.io/ --silent | grep Age
Age: 0
 $ curl -I http://dev-pantheon-integrated-cdn.pantheonsite.io/2016/11/03/post-2 --silent | grep Age
Age: 0
$ curl -I http://dev-pantheon-integrated-cdn.pantheonsite.io/2016/11/03/post-1 --silent | grep Age
Age: 0

**Comment by danielbachhuber** [comment]
Thanks for the report, @ari-gold. To begin with, I've added [explicit assertions of affected URIs](https://github.com/pantheon-systems/pantheon-integrated-cdn/blob/9229d6078e1296af5afe3e7226a64128813fda93/tests/phpunit/test-purger.php#L24-L34) which each of our purge events occurs.

**Comment by danielbachhuber** [comment]
@ari-gold The fix is now on the dev environment.

**Comment by ari-gold** [comment]
We discovered this still happens when both posts are in the same category, e.g. Uncatagorized.

**Comment by danielbachhuber** [comment]
> We discovered this still happens when both posts are in the same category, e.g. Uncategorized.

@ari-gold I've uploaded the latest version to the testing environment, with a fix for this issue.

**Comment by ari-gold** [comment]
Confirmed fixed. Thanks @danielbachhuber !
