### ISSUE TITLE
Admin UI update

### ISSUE THREAD

**Issue by ari-gold** [pantheon-systems/pantheon-advanced-page-cache#70]
<img width="955" alt="screenshot 2016-11-29 12 57 24" src="https://cloud.githubusercontent.com/assets/7874556/20728885/a64915dc-b634-11e6-812f-b35c143243c2.png">

Pantheon Advanced Page Cache activated. [Learn more](https://github.com/pantheon-systems/pantheon-advanced-page-cache)

**Comment by danielbachhuber** [comment]
@ari-gold This is now live on http://dev-pantheon-advanced-page-cache.pantheonsite.io/wp-admin/options-general.php?page=pantheon-cache
