### ISSUE TITLE
Updates made in admin interface not showing up

### ISSUE THREAD

**Issue by newtoid** [pantheon-systems/pantheon-advanced-page-cache#81]
Client site updated to latest WP version a couple of days ago and has since reported that updates made in the UI to settings including enabling/disabling plugins, setting TTL in Pantheon APC, and reordering menus, are not persisting when saved.

Sometimes this issue clears after 15 minutes, or after repeated cache clears.

This is also preventing users from updating content.

Is there any possibility this is related to recent updates to either the plugin or WP core?

**Comment by ari-gold** [comment]
I can't reproduce, using latest version of plugin with latest version of WP core.

http://g.recordit.co/fh1IL1LH9l.gif

**Comment by newtoid** [comment]
Thanks @ari-gold, turns out it is a known issue in WP core that causes the problem - https://github.com/pantheon-systems/wp-redis/issues/111, https://core.trac.wordpress.org/ticket/31245
