### ISSUE TITLE
RSS Feed not purging on content updates

### ISSUE THREAD

**Issue by bbenjamin** [pantheon-systems/pantheon-advanced-page-cache#82]
I may have an explanation and I'll likely make an attempt at fixing it - I looked at the surrogate keys on the RSS feeds for my two Pantheon wordpress sites, and noticed it is only 'post-*' keys. Based on  my understanding of the plugin, I think this would mean the RSS feed would only get purged if content already present in the feed was updated - there's no surrogate key to indicate that it's a collection of data. 

I'm going to see if this can be addressed by adding a surrogate key to RSS - perhaps just adding 'front' will take care of it. Let me know if this seems like a valid approach.

**Comment by bbenjamin** [comment]
Added my fix to pull request https://github.com/pantheon-systems/pantheon-advanced-page-cache/pull/83

**Comment by danielbachhuber** [comment]
> Based on my understanding of the plugin, I think this would mean the RSS feed would only get purged if content already present in the feed was updated

I agree with this assessment. New release coming shortly.
