### ISSUE TITLE
Possible Cache Key Stampede w/WooCommerce

### ISSUE THREAD

**Issue by joshkoenig** [pantheon-systems/pantheon-advanced-page-cache#86]
Got an issue where cache key expiration is happening as part of the WooCommerce checkout process, and potentially causing a difficult surge of key expirations:

![screen shot 2017-03-20 at 11 25 18 am](https://cloud.githubusercontent.com/assets/143186/24116065/b2ffecd0-0d62-11e7-8c12-58662d21e457.png)

When the site is only handling 10s of requests per minute, it's unexpected for there to be 1000s of cache expiration calls. We need to look into this internally since it may be an artifact of how our `curl_multi_exec()` is structured, but it seems worthwhile to investigate this rate of cache clearing on WooCommerce. Might be ripe for some optimization.

**Comment by danielbachhuber** [comment]
> Got an issue where cache key expiration is happening as part of the WooCommerce checkout process, and potentially causing a difficult surge of key expirations:

Is there any way you could get a stacktrace when this is happening?

> When the site is only handling 10s of requests per minute, it's unexpected for there to be 1000s of cache expiration calls.

Could be a bad actor supplementary plugin again, a la ACF.

> We need to look into this internally since it may be an artifact of how our `curl_multi_exec()` is structured, but it seems worthwhile to investigate this rate of cache clearing on WooCommerce. Might be ripe for some optimization.

PAPC could hold all purge calls until `shutdown` and then perform in one request, but I'd think `pantheon_clear_edge_keys()` could do this too.

**Comment by danielbachhuber** [comment]
I did a hangout with the customer today and we weren't able to reproduce the issue.

According to his report, there are two scenarios where this issue happens most commonly:

1. An hourly WP Cron job that syncs WooCommerce data to an external service.
2. As a part of the checkout process. User hits submit and waits for 40s while WordPress handles the form submission.

My hypothesis is that WordPress + all of the plugins installed are triggering a huge number of cache clear events, which corresponding incurs a large number of key purge calls.

If this is the case, the best solution I have in mind is to batch the key purge calls. For instance, 10 calls to `pantheon_wp_clear_edge_keys()` during a request would be held to shutdown. Then, on shutdown the plugin would call `pantheon_clear_edge_keys()` with all of the keys that had been passed to `pantheon_wp_clear_edge_keys()`.

**Comment by danielbachhuber** [comment]
This is now fixed at the platform-level: https://github.com/pantheon-systems/pantheon-advanced-page-cache/issues/95#issuecomment-327240283
