### ISSUE TITLE
Would it work outside Pantheon?

### ISSUE THREAD

**Issue by TangRufus** [pantheon-systems/pantheon-advanced-page-cache#87]
Would it work outside Pantheon? Or, what's the minimum requirement to get it work?

Thank!

**Comment by danielbachhuber** [comment]
> Would it work outside Pantheon?

Probably not without substantial development effort.

> Or, what's the minimum requirement to get it work?

You'd need to implement a full page cache layer with tagging mechanism (Varnish or similar), and then create `pantheon_clear_edge_keys()`, `pantheon_clear_edge_paths()`, and `pantheon_clear_edge_all()` functions to interface with the cache layer.

Pantheon Advanced Page Cache is simply an integration layer that calls aforementioned functions.

**Comment by TangRufus** [comment]
Thx
