### ISSUE TITLE
503 first byte timeout when saving a large menu

### ISSUE THREAD

**Issue by alexdicianu** [pantheon-systems/pantheon-advanced-page-cache#95]
Saving a large menu (with 100 or more items) causes a 503 first byte timeout. The entry from the php-slow.log below seems to indicate that there's a high number of external calls to purge all those urls. While each individual call is fairly fast, they all add up.

```
[12-Jul-2017 11:17:05]  [pool www] pid 25642
--
  | script_filename = /srv/bindings/6817d893a49b4d8bb4776b563bd726ac/code//wp-admin/nav-menus.php
  | [0x00007f4c85c155e0] curl_multi_select() /srv/includes/pantheon.php:317
  | [0x00007f4c85c15430] pantheon_multi_curl() /srv/includes/pantheon.php:611
  | [0x00007f4c85c15320] pantheon_clear_edge_keys() /srv/bindings/6817d893a49b4d8bb4776b563bd726ac/code/wp-content/plugins/pantheon-advanced-page-cache/pantheon-advanced-page-cache.php:31
  | [0x00007f4c85c15280] pantheon_wp_clear_edge_keys() /srv/bindings/6817d893a49b4d8bb4776b563bd726ac/code/wp-content/plugins/pantheon-advanced-page-cache/inc/class-purger.php:188
  | [0x00007f4c85c15180] purge_post_with_related() /srv/bindings/6817d893a49b4d8bb4776b563bd726ac/code/wp-content/plugins/pantheon-advanced-page-cache/inc/class-purger.php:39
  | [0x00007f4c85c150b0] action_transition_post_status() /srv/bindings/6817d893a49b4d8bb4776b563bd726ac/code/wp-includes/class-wp-hook.php:298
  | [0x00007f4c85c14fc0] apply_filters() /srv/bindings/6817d893a49b4d8bb4776b563bd726ac/code/wp-includes/class-wp-hook.php:323
  | [0x00007f4c85c14f40] do_action() /srv/bindings/6817d893a49b4d8bb4776b563bd726ac/code/wp-includes/plugin.php:453
  | [0x00007f4c85c14e00] do_action() /srv/bindings/6817d893a49b4d8bb4776b563bd726ac/code/wp-includes/post.php:3965
  | [0x00007f4c85c14d30] wp_transition_post_status() /srv/bindings/6817d893a49b4d8bb4776b563bd726ac/code/wp-includes/post.php:3425
  | [0x00007f4c85c14920] wp_insert_post() /srv/bindings/6817d893a49b4d8bb4776b563bd726ac/code/wp-includes/post.php:3583
  | [0x00007f4c85c14840] wp_update_post() /srv/bindings/6817d893a49b4d8bb4776b563bd726ac/code/wp-includes/nav-menu.php:514
  | [0x00007f4c85c146e0] wp_update_nav_menu_item() /srv/bindings/6817d893a49b4d8bb4776b563bd726ac/code/wp-admin/includes/nav-menu.php:1042
  | [0x00007f4c85c14540] wp_nav_menu_update_menu_items() /srv/bindings/6817d893a49b4d8bb4776b563bd726ac/code/wp-admin/nav-menus.php:368

```

**Comment by danielbachhuber** [comment]
> Saving a large menu (with 100 or more items) causes a 503 first byte timeout.

I was able to easily reproduce this in a test environment.

Because nav menu items are never a part of a main `WP_Query`, we may be able to get away with not triggering purge events when nav menus are updated. But, that could potentially leave REST API endpoints stale.

**Comment by joshkoenig** [comment]
We're going to look at batching purge requests at the platform level. If that is a good possibility, we may be able to fix this "below" the WordPress plugin level. Stay tuned for updates.

**Comment by stevector** [comment]
FWIW, I was able to replicate similar errors in the Drupal module by using devel_generate module to generate hundreds of items of content, taxonomy terms, menu items, etc.

**Comment by JoshShashaty** [comment]
Found this issue while looking for the problem.  Found it in new relic.

Screenshot if it helps: https://i.imgur.com/Ix1Dyxw.png

**Comment by danielbachhuber** [comment]
@JoshShashaty Thanks for the details.

There's some Pantheon platform work currently in progress to address this issue. It'll most likely be resolved at the platform level and we'll update this issue when there's more to report.

**Comment by jdleonard** [comment]
pantheon_clear_edge_keys() is resulting in degraded performance (but not 503s) on a Drupal site. I assume that batching the purge requests will resolve this.

**Comment by jcowher** [comment]
Looking into the [API documentation](https://docs.fastly.com/api/purge#purge_db35b293f8a724717fcf25628d713583) for Fastly, it seems only up to 256 surrogate keys can be purged at once. As an interim solution, surrogate keys could be split into chunks, for example:

```
if ( function_exists( 'pantheon_wp_clear_edge_keys' ) ) {
    $chunks = array_chunk( $surrogate_keys, 256 );
    foreach ( $chunks as $chunk ) {
        $status = pantheon_wp_clear_edge_keys( $chunk );
        if ( is_wp_error( $status ) ) {
            // Do something on error
        }
    }
}
```

The purge process for ~1000 posts is a bit slow (~10 seconds), but appears to be working in our use-case (re-ordering pages via drag 'n drop).

**Comment by ari-gold** [comment]
Today we deployed a fix at the platform-level to fix this issue.

**Comment by jdleonard** [comment]
@ari-gold After your comment about the deployment, I started seeing the following error in my Pantheon dashboard:

> Uncaught Error: Call to undefined function pantheon_clear_edge_keys_collector() in /srv/includes/pantheon.php:622
> Stack trace:
> #0 [internal function]: pantheon_clear_edge_keys_shutdown()
> #1 {main}
> thrown

![image](https://user-images.githubusercontent.com/2074112/30073849-5bb3fb32-923d-11e7-81c5-5aac2b91034b.png)

**Comment by ari-gold** [comment]
@jdleonard  I can't reproduce. It looks like you're using a dark-deployed function that no longer exists, and that there may have been some confusion with support guiding you to the dark deployed function. Are you using the standard release of this plugin? Please open up a chat/ticket with support if you need further assistance.
