### ISSUE TITLE
Document how to exempt pages

### ISSUE THREAD

**Issue by Shelob9** [pantheon-systems/pantheon-advanced-page-cache#97]
I'm looking to exempt checkout/cart pages for Easy Digital Downloads, but can't figure out how from docs, will look for filters.

**Comment by danielbachhuber** [comment]
Hi @Shelob9,

If you're looking to except checkout/cart pages from caching, you can do so by sending the no-cache header. Here's an illustrative code snippet:

```
/**
 * Disable full page cache for requests to /cart/
 *
 * With great power comes great responsibility. Please
 * be conservative with how you disable cache and test
 * thoroughly.
 */
add_filter( 'wp_headers', function( $headers, $wp ) {
	// $wp->request contains matched rewrite rule: 'cart'
	if ( 0 === stripos( $wp->request, 'cart' ) ) {
		$headers = array_merge( $headers, wp_get_nocache_headers() );
	}
	return $headers;
}, 10, 2 );
```

Let me know if there's something further you're looking for.

**Comment by Shelob9** [comment]
@danielbachhuber That's perfect. Shouldn't this go in the docs? 

I actually solved this by writing a new cookie when contents were added to EDD cart, but I will test your solution for account/ purchase complete pages/ etc.

```
/**
 * Write _cfdc_cart cookie on add to cart click
 */
add_action( 'wp_footer', function(){
	?>
	<script>jQuery( '.edd-add-to-cart' ).on( 'click', function(){document.cookie = "_cfdc_cart=1";});</script>
	<?php
});

/**
 * Write _cfdc_cart cookie on add to cart hook
 */
add_action( 'edd_pre_add_to_cart', function(){
	setcookie( '_cfdc_cart', 1, time()+2* DAY_IN_SECONDS, COOKIEPATH, COOKIE_DOMAIN, false);
} );
```

BTW For the sake of of future Googlers -- you spelled `strpos()` wrong.

**Comment by danielbachhuber** [comment]
> Shouldn't this go in the docs?

I thought about it but decided this isn't something we want to actively encourage.

We want users to use the page cache as much as possible. If they're having some issue unrelated to full page cache but they think they can fix it by disabling cache, I'd rather not encourage them to disable cache.

> I actually solved this by writing a new cookie when contents were added to EDD cart

Note: this approach won't actually work on Pantheon because `_cfdc_cart` doesn't bust the cache. Only a whitelisted set of cookies cause a request to bypass the cache.

> BTW For the sake of of future Googlers -- you spelled `strpos()` wrong.

`stripos()` is case-insensitive searching: http://php.net/manual/en/function.stripos.php

**Comment by Shelob9** [comment]
@danielbachhuber Using an arbitrary cookie worked on our site, is there a better cookie to use?

Also TIL `stripos()` is a thing, neato.

**Comment by danielbachhuber** [comment]
> is there a better cookie to use?

I think sending no-cache headers is more appropriate for your use case.
